/****************************************************************************
**
** Metadata for RPCLib generated by dumpcpp v5.12.8 using
** dumpcpp.exe RPC.tlb
** from the type library RPC.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_RPCLIB_NOINLINES
#include "rpclib.h"

using namespace RPCLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[345];
    char stringdata0[5305];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 27, 0),
QT_MOC_LITERAL(1, 28, 11, 0),
QT_MOC_LITERAL(2, 40, 20, 0),
QT_MOC_LITERAL(3, 61, 9, 0),
QT_MOC_LITERAL(4, 71, 0, 0),
QT_MOC_LITERAL(5, 72, 4, 0),
QT_MOC_LITERAL(6, 77, 6, 0),
QT_MOC_LITERAL(7, 84, 4, 0),
QT_MOC_LITERAL(8, 89, 4, 0),
QT_MOC_LITERAL(9, 94, 15, 0),
QT_MOC_LITERAL(10, 110, 4, 0),
QT_MOC_LITERAL(11, 115, 6, 0),
QT_MOC_LITERAL(12, 122, 4, 0),
QT_MOC_LITERAL(13, 127, 4, 0),
QT_MOC_LITERAL(14, 132, 24, 0),
QT_MOC_LITERAL(15, 157, 5, 0),
QT_MOC_LITERAL(16, 163, 20, 0),
QT_MOC_LITERAL(17, 184, 16, 0),
QT_MOC_LITERAL(18, 201, 19, 0),
QT_MOC_LITERAL(19, 221, 15, 0),
QT_MOC_LITERAL(20, 237, 26, 0),
QT_MOC_LITERAL(21, 264, 24, 0),
QT_MOC_LITERAL(22, 289, 11, 0),
QT_MOC_LITERAL(23, 301, 9, 0),
QT_MOC_LITERAL(24, 311, 11, 0),
QT_MOC_LITERAL(25, 323, 9, 0),
QT_MOC_LITERAL(26, 333, 9, 0),
QT_MOC_LITERAL(27, 343, 13, 0),
QT_MOC_LITERAL(28, 357, 22, 0),
QT_MOC_LITERAL(29, 380, 10, 0),
QT_MOC_LITERAL(30, 391, 10, 0),
QT_MOC_LITERAL(31, 402, 4, 0),
QT_MOC_LITERAL(32, 407, 10, 0),
QT_MOC_LITERAL(33, 418, 21, 0),
QT_MOC_LITERAL(34, 440, 20, 0),
QT_MOC_LITERAL(35, 461, 14, 0),
QT_MOC_LITERAL(36, 476, 7, 0),
QT_MOC_LITERAL(37, 484, 10, 0),
QT_MOC_LITERAL(38, 495, 14, 0),
QT_MOC_LITERAL(39, 510, 7, 0),
QT_MOC_LITERAL(40, 518, 8, 0),
QT_MOC_LITERAL(41, 527, 26, 0),
QT_MOC_LITERAL(42, 554, 10, 0),
QT_MOC_LITERAL(43, 565, 28, 0),
QT_MOC_LITERAL(44, 594, 16, 0),
QT_MOC_LITERAL(45, 611, 6, 0),
QT_MOC_LITERAL(46, 618, 18, 0),
QT_MOC_LITERAL(47, 637, 12, 0),
QT_MOC_LITERAL(48, 650, 8, 0),
QT_MOC_LITERAL(49, 659, 7, 0),
QT_MOC_LITERAL(50, 667, 18, 0),
QT_MOC_LITERAL(51, 686, 7, 0),
QT_MOC_LITERAL(52, 694, 8, 0),
QT_MOC_LITERAL(53, 703, 6, 0),
QT_MOC_LITERAL(54, 710, 23, 0),
QT_MOC_LITERAL(55, 734, 9, 0),
QT_MOC_LITERAL(56, 744, 8, 0),
QT_MOC_LITERAL(57, 753, 18, 0),
QT_MOC_LITERAL(58, 772, 14, 0),
QT_MOC_LITERAL(59, 787, 17, 0),
QT_MOC_LITERAL(60, 805, 13, 0),
QT_MOC_LITERAL(61, 819, 16, 0),
QT_MOC_LITERAL(62, 836, 8, 0),
QT_MOC_LITERAL(63, 845, 19, 0),
QT_MOC_LITERAL(64, 865, 19, 0),
QT_MOC_LITERAL(65, 885, 20, 0),
QT_MOC_LITERAL(66, 906, 11, 0),
QT_MOC_LITERAL(67, 918, 6, 0),
QT_MOC_LITERAL(68, 925, 22, 0),
QT_MOC_LITERAL(69, 948, 11, 0),
QT_MOC_LITERAL(70, 960, 14, 0),
QT_MOC_LITERAL(71, 975, 22, 0),
QT_MOC_LITERAL(72, 998, 6, 0),
QT_MOC_LITERAL(73, 1005, 22, 0),
QT_MOC_LITERAL(74, 1028, 22, 0),
QT_MOC_LITERAL(75, 1051, 26, 0),
QT_MOC_LITERAL(76, 1078, 11, 0),
QT_MOC_LITERAL(77, 1090, 10, 0),
QT_MOC_LITERAL(78, 1101, 17, 0),
QT_MOC_LITERAL(79, 1119, 4, 0),
QT_MOC_LITERAL(80, 1124, 4, 0),
QT_MOC_LITERAL(81, 1129, 4, 0),
QT_MOC_LITERAL(82, 1134, 18, 0),
QT_MOC_LITERAL(83, 1153, 9, 0),
QT_MOC_LITERAL(84, 1163, 17, 0),
QT_MOC_LITERAL(85, 1181, 17, 0),
QT_MOC_LITERAL(86, 1199, 8, 0),
QT_MOC_LITERAL(87, 1208, 16, 0),
QT_MOC_LITERAL(88, 1225, 16, 0),
QT_MOC_LITERAL(89, 1242, 8, 0),
QT_MOC_LITERAL(90, 1251, 19, 0),
QT_MOC_LITERAL(91, 1271, 19, 0),
QT_MOC_LITERAL(92, 1291, 20, 0),
QT_MOC_LITERAL(93, 1312, 11, 0),
QT_MOC_LITERAL(94, 1324, 22, 0),
QT_MOC_LITERAL(95, 1347, 7, 0),
QT_MOC_LITERAL(96, 1355, 36, 0),
QT_MOC_LITERAL(97, 1392, 7, 0),
QT_MOC_LITERAL(98, 1400, 14, 0),
QT_MOC_LITERAL(99, 1415, 20, 0),
QT_MOC_LITERAL(100, 1436, 14, 0),
QT_MOC_LITERAL(101, 1451, 10, 0),
QT_MOC_LITERAL(102, 1462, 14, 0),
QT_MOC_LITERAL(103, 1477, 10, 0),
QT_MOC_LITERAL(104, 1488, 19, 0),
QT_MOC_LITERAL(105, 1508, 10, 0),
QT_MOC_LITERAL(106, 1519, 15, 0),
QT_MOC_LITERAL(107, 1535, 11, 0),
QT_MOC_LITERAL(108, 1547, 13, 0),
QT_MOC_LITERAL(109, 1561, 9, 0),
QT_MOC_LITERAL(110, 1571, 19, 0),
QT_MOC_LITERAL(111, 1591, 11, 0),
QT_MOC_LITERAL(112, 1603, 15, 0),
QT_MOC_LITERAL(113, 1619, 16, 0),
QT_MOC_LITERAL(114, 1636, 13, 0),
QT_MOC_LITERAL(115, 1650, 11, 0),
QT_MOC_LITERAL(116, 1662, 19, 0),
QT_MOC_LITERAL(117, 1682, 10, 0),
QT_MOC_LITERAL(118, 1693, 10, 0),
QT_MOC_LITERAL(119, 1704, 8, 0),
QT_MOC_LITERAL(120, 1713, 18, 0),
QT_MOC_LITERAL(121, 1732, 10, 0),
QT_MOC_LITERAL(122, 1743, 14, 0),
QT_MOC_LITERAL(123, 1758, 14, 0),
QT_MOC_LITERAL(124, 1773, 15, 0),
QT_MOC_LITERAL(125, 1789, 18, 0),
QT_MOC_LITERAL(126, 1808, 9, 0),
QT_MOC_LITERAL(127, 1818, 8, 0),
QT_MOC_LITERAL(128, 1827, 9, 0),
QT_MOC_LITERAL(129, 1837, 10, 0),
QT_MOC_LITERAL(130, 1848, 8, 0),
QT_MOC_LITERAL(131, 1857, 21, 0),
QT_MOC_LITERAL(132, 1879, 9, 0),
QT_MOC_LITERAL(133, 1889, 10, 0),
QT_MOC_LITERAL(134, 1900, 11, 0),
QT_MOC_LITERAL(135, 1912, 8, 0),
QT_MOC_LITERAL(136, 1921, 11, 0),
QT_MOC_LITERAL(137, 1933, 23, 0),
QT_MOC_LITERAL(138, 1957, 12, 0),
QT_MOC_LITERAL(139, 1970, 11, 0),
QT_MOC_LITERAL(140, 1982, 8, 0),
QT_MOC_LITERAL(141, 1991, 15, 0),
QT_MOC_LITERAL(142, 2007, 16, 0),
QT_MOC_LITERAL(143, 2024, 33, 0),
QT_MOC_LITERAL(144, 2058, 10, 0),
QT_MOC_LITERAL(145, 2069, 16, 0),
QT_MOC_LITERAL(146, 2086, 23, 0),
QT_MOC_LITERAL(147, 2110, 14, 0),
QT_MOC_LITERAL(148, 2125, 11, 0),
QT_MOC_LITERAL(149, 2137, 20, 0),
QT_MOC_LITERAL(150, 2158, 6, 0),
QT_MOC_LITERAL(151, 2165, 23, 0),
QT_MOC_LITERAL(152, 2189, 9, 0),
QT_MOC_LITERAL(153, 2199, 10, 0),
QT_MOC_LITERAL(154, 2210, 9, 0),
QT_MOC_LITERAL(155, 2220, 14, 0),
QT_MOC_LITERAL(156, 2235, 14, 0),
QT_MOC_LITERAL(157, 2250, 20, 0),
QT_MOC_LITERAL(158, 2271, 11, 0),
QT_MOC_LITERAL(159, 2283, 32, 0),
QT_MOC_LITERAL(160, 2316, 11, 0),
QT_MOC_LITERAL(161, 2328, 13, 0),
QT_MOC_LITERAL(162, 2342, 16, 0),
QT_MOC_LITERAL(163, 2359, 31, 0),
QT_MOC_LITERAL(164, 2391, 7, 0),
QT_MOC_LITERAL(165, 2399, 21, 0),
QT_MOC_LITERAL(166, 2421, 18, 0),
QT_MOC_LITERAL(167, 2440, 9, 0),
QT_MOC_LITERAL(168, 2450, 28, 0),
QT_MOC_LITERAL(169, 2479, 5, 0),
QT_MOC_LITERAL(170, 2485, 17, 0),
QT_MOC_LITERAL(171, 2503, 10, 0),
QT_MOC_LITERAL(172, 2514, 11, 0),
QT_MOC_LITERAL(173, 2526, 17, 0),
QT_MOC_LITERAL(174, 2544, 15, 0),
QT_MOC_LITERAL(175, 2560, 15, 0),
QT_MOC_LITERAL(176, 2576, 15, 0),
QT_MOC_LITERAL(177, 2592, 11, 0),
QT_MOC_LITERAL(178, 2604, 11, 0),
QT_MOC_LITERAL(179, 2616, 10, 0),
QT_MOC_LITERAL(180, 2627, 16, 0),
QT_MOC_LITERAL(181, 2644, 12, 0),
QT_MOC_LITERAL(182, 2657, 29, 0),
QT_MOC_LITERAL(183, 2687, 22, 0),
QT_MOC_LITERAL(184, 2710, 8, 0),
QT_MOC_LITERAL(185, 2719, 27, 0),
QT_MOC_LITERAL(186, 2747, 23, 0),
QT_MOC_LITERAL(187, 2771, 11, 0),
QT_MOC_LITERAL(188, 2783, 11, 0),
QT_MOC_LITERAL(189, 2795, 10, 0),
QT_MOC_LITERAL(190, 2806, 11, 0),
QT_MOC_LITERAL(191, 2818, 17, 0),
QT_MOC_LITERAL(192, 2836, 22, 0),
QT_MOC_LITERAL(193, 2859, 12, 0),
QT_MOC_LITERAL(194, 2872, 18, 0),
QT_MOC_LITERAL(195, 2891, 15, 0),
QT_MOC_LITERAL(196, 2907, 19, 0),
QT_MOC_LITERAL(197, 2927, 10, 0),
QT_MOC_LITERAL(198, 2938, 15, 0),
QT_MOC_LITERAL(199, 2954, 11, 0),
QT_MOC_LITERAL(200, 2966, 27, 0),
QT_MOC_LITERAL(201, 2994, 28, 0),
QT_MOC_LITERAL(202, 3023, 11, 0),
QT_MOC_LITERAL(203, 3035, 12, 0),
QT_MOC_LITERAL(204, 3048, 17, 0),
QT_MOC_LITERAL(205, 3066, 25, 0),
QT_MOC_LITERAL(206, 3092, 9, 0),
QT_MOC_LITERAL(207, 3102, 9, 0),
QT_MOC_LITERAL(208, 3112, 9, 0),
QT_MOC_LITERAL(209, 3122, 23, 0),
QT_MOC_LITERAL(210, 3146, 15, 0),
QT_MOC_LITERAL(211, 3162, 8, 0),
QT_MOC_LITERAL(212, 3171, 8, 0),
QT_MOC_LITERAL(213, 3180, 8, 0),
QT_MOC_LITERAL(214, 3189, 6, 0),
QT_MOC_LITERAL(215, 3196, 6, 0),
QT_MOC_LITERAL(216, 3203, 6, 0),
QT_MOC_LITERAL(217, 3210, 20, 0),
QT_MOC_LITERAL(218, 3231, 11, 0),
QT_MOC_LITERAL(219, 3243, 20, 0),
QT_MOC_LITERAL(220, 3264, 14, 0),
QT_MOC_LITERAL(221, 3279, 19, 0),
QT_MOC_LITERAL(222, 3299, 11, 0),
QT_MOC_LITERAL(223, 3311, 21, 0),
QT_MOC_LITERAL(224, 3333, 18, 0),
QT_MOC_LITERAL(225, 3352, 16, 0),
QT_MOC_LITERAL(226, 3369, 13, 0),
QT_MOC_LITERAL(227, 3383, 9, 0),
QT_MOC_LITERAL(228, 3393, 17, 0),
QT_MOC_LITERAL(229, 3411, 26, 0),
QT_MOC_LITERAL(230, 3438, 11, 0),
QT_MOC_LITERAL(231, 3450, 11, 0),
QT_MOC_LITERAL(232, 3462, 11, 0),
QT_MOC_LITERAL(233, 3474, 11, 0),
QT_MOC_LITERAL(234, 3486, 24, 0),
QT_MOC_LITERAL(235, 3511, 20, 0),
QT_MOC_LITERAL(236, 3532, 11, 0),
QT_MOC_LITERAL(237, 3544, 12, 0),
QT_MOC_LITERAL(238, 3557, 16, 0),
QT_MOC_LITERAL(239, 3574, 17, 0),
QT_MOC_LITERAL(240, 3592, 17, 0),
QT_MOC_LITERAL(241, 3610, 13, 0),
QT_MOC_LITERAL(242, 3624, 13, 0),
QT_MOC_LITERAL(243, 3638, 8, 0),
QT_MOC_LITERAL(244, 3647, 22, 0),
QT_MOC_LITERAL(245, 3670, 7, 0),
QT_MOC_LITERAL(246, 3678, 22, 0),
QT_MOC_LITERAL(247, 3701, 12, 0),
QT_MOC_LITERAL(248, 3714, 11, 0),
QT_MOC_LITERAL(249, 3726, 11, 0),
QT_MOC_LITERAL(250, 3738, 23, 0),
QT_MOC_LITERAL(251, 3762, 13, 0),
QT_MOC_LITERAL(252, 3776, 12, 0),
QT_MOC_LITERAL(253, 3789, 19, 0),
QT_MOC_LITERAL(254, 3809, 20, 0),
QT_MOC_LITERAL(255, 3830, 24, 0),
QT_MOC_LITERAL(256, 3855, 15, 0),
QT_MOC_LITERAL(257, 3871, 17, 0),
QT_MOC_LITERAL(258, 3889, 24, 0),
QT_MOC_LITERAL(259, 3914, 10, 0),
QT_MOC_LITERAL(260, 3925, 28, 0),
QT_MOC_LITERAL(261, 3954, 12, 0),
QT_MOC_LITERAL(262, 3967, 6, 0),
QT_MOC_LITERAL(263, 3974, 8, 0),
QT_MOC_LITERAL(264, 3983, 11, 0),
QT_MOC_LITERAL(265, 3995, 22, 0),
QT_MOC_LITERAL(266, 4018, 18, 0),
QT_MOC_LITERAL(267, 4037, 18, 0),
QT_MOC_LITERAL(268, 4056, 23, 0),
QT_MOC_LITERAL(269, 4080, 22, 0),
QT_MOC_LITERAL(270, 4103, 10, 0),
QT_MOC_LITERAL(271, 4114, 25, 0),
QT_MOC_LITERAL(272, 4140, 13, 0),
QT_MOC_LITERAL(273, 4154, 12, 0),
QT_MOC_LITERAL(274, 4167, 17, 0),
QT_MOC_LITERAL(275, 4185, 12, 0),
QT_MOC_LITERAL(276, 4198, 11, 0),
QT_MOC_LITERAL(277, 4210, 23, 0),
QT_MOC_LITERAL(278, 4234, 13, 0),
QT_MOC_LITERAL(279, 4248, 8, 0),
QT_MOC_LITERAL(280, 4257, 10, 0),
QT_MOC_LITERAL(281, 4268, 25, 0),
QT_MOC_LITERAL(282, 4294, 11, 0),
QT_MOC_LITERAL(283, 4306, 25, 0),
QT_MOC_LITERAL(284, 4332, 15, 0),
QT_MOC_LITERAL(285, 4348, 21, 0),
QT_MOC_LITERAL(286, 4370, 14, 0),
QT_MOC_LITERAL(287, 4385, 10, 0),
QT_MOC_LITERAL(288, 4396, 12, 0),
QT_MOC_LITERAL(289, 4409, 11, 0),
QT_MOC_LITERAL(290, 4421, 12, 0),
QT_MOC_LITERAL(291, 4434, 20, 0),
QT_MOC_LITERAL(292, 4455, 5, 0),
QT_MOC_LITERAL(293, 4461, 15, 0),
QT_MOC_LITERAL(294, 4477, 20, 0),
QT_MOC_LITERAL(295, 4498, 13, 0),
QT_MOC_LITERAL(296, 4512, 17, 0),
QT_MOC_LITERAL(297, 4530, 16, 0),
QT_MOC_LITERAL(298, 4547, 11, 0),
QT_MOC_LITERAL(299, 4559, 26, 0),
QT_MOC_LITERAL(300, 4586, 10, 0),
QT_MOC_LITERAL(301, 4597, 11, 0),
QT_MOC_LITERAL(302, 4609, 9, 0),
QT_MOC_LITERAL(303, 4619, 19, 0),
QT_MOC_LITERAL(304, 4639, 19, 0),
QT_MOC_LITERAL(305, 4659, 16, 0),
QT_MOC_LITERAL(306, 4676, 18, 0),
QT_MOC_LITERAL(307, 4695, 5, 0),
QT_MOC_LITERAL(308, 4701, 22, 0),
QT_MOC_LITERAL(309, 4724, 24, 0),
QT_MOC_LITERAL(310, 4749, 29, 0),
QT_MOC_LITERAL(311, 4779, 9, 0),
QT_MOC_LITERAL(312, 4789, 11, 0),
QT_MOC_LITERAL(313, 4801, 5, 0),
QT_MOC_LITERAL(314, 4807, 13, 0),
QT_MOC_LITERAL(315, 4821, 11, 0),
QT_MOC_LITERAL(316, 4833, 6, 0),
QT_MOC_LITERAL(317, 4840, 6, 0),
QT_MOC_LITERAL(318, 4847, 7, 0),
QT_MOC_LITERAL(319, 4855, 8, 0),
QT_MOC_LITERAL(320, 4864, 10, 0),
QT_MOC_LITERAL(321, 4875, 7, 0),
QT_MOC_LITERAL(322, 4883, 28, 0),
QT_MOC_LITERAL(323, 4912, 7, 0),
QT_MOC_LITERAL(324, 4920, 36, 0),
QT_MOC_LITERAL(325, 4957, 19, 0),
QT_MOC_LITERAL(326, 4977, 11, 0),
QT_MOC_LITERAL(327, 4989, 13, 0),
QT_MOC_LITERAL(328, 5003, 19, 0),
QT_MOC_LITERAL(329, 5023, 22, 0),
QT_MOC_LITERAL(330, 5046, 15, 0),
QT_MOC_LITERAL(331, 5062, 7, 0),
QT_MOC_LITERAL(332, 5070, 7, 0),
QT_MOC_LITERAL(333, 5078, 17, 0),
QT_MOC_LITERAL(334, 5096, 12, 0),
QT_MOC_LITERAL(335, 5109, 13, 0),
QT_MOC_LITERAL(336, 5123, 10, 0),
QT_MOC_LITERAL(337, 5134, 25, 0),
QT_MOC_LITERAL(338, 5160, 10, 0),
QT_MOC_LITERAL(339, 5171, 8, 0),
QT_MOC_LITERAL(340, 5180, 15, 0),
QT_MOC_LITERAL(341, 5196, 18, 0),
QT_MOC_LITERAL(342, 5215, 23, 0),
QT_MOC_LITERAL(343, 5239, 35, 0),
QT_MOC_LITERAL(344, 5275, 28, 0)
    },
    "RPCLib::PQPlatformComponent\0Interface 0\0IPQPlatformComponent\0exception\0\0code\0"
    "source\0disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0Doc_add_sim_collide_data\0"
    "uint&\0i_vCollisionCheckIDS\0i_nCheckIDSCount\0i_vCollisionWithIDS\0i_nWithIDSCount\0"
    "Doc_clear_sim_collide_data\0Doc_collide_obj_multiple\0i_ulObjAIDs\0i_nACount\0"
    "i_ulObjBIDs\0i_nBCount\0QVariant&\0o_collideObjs\0Doc_collide_obj_single\0i_ulObjAID\0"
    "i_ulObjBID\0int&\0o_bCollide\0Doc_create_coordinate\0i_ulBaseCoordinateID\0"
    "i_nPostureType\0double&\0i_dPosture\0i_nPostureSize\0wint_t*\0i_chName\0"
    "Doc_get_coordinate_posture\0i_ulCoorID\0Doc_get_current_selected_obj\0"
    "o_nSelectedCount\0uint**\0o_ulSelectedObjIDs\0Doc_get_name\0QString&\0o_sName\0"
    "Doc_get_obj_bytype\0i_lType\0o_sNames\0o_sIDs\0Doc_get_obj_joint_count\0i_ulObjID\0"
    "o_nCount\0Doc_get_obj_joints\0i_nJointsCount\0Doc_get_obj_links\0o_nLinksCount\0"
    "Doc_get_obj_name\0o_bsName\0Doc_get_obj_posture\0o_nPostureArraySize\0"
    "Doc_get_obj_velocity\0o_dVelocity\0o_dRAD\0Doc_get_pathgroup_name\0i_ulRobotID\0"
    "o_varNameArray\0Doc_obj_rotate_local_X\0i_dRAD\0Doc_obj_rotate_local_Y\0"
    "Doc_obj_rotate_local_Z\0Doc_set_dockwindow_visible\0i_nDockType\0i_bVisible\0"
    "Doc_set_obj_color\0i_dR\0i_dG\0i_dB\0Doc_set_obj_joints\0i_dJoints\0i_nJointArraySize\0"
    "Doc_set_obj_links\0i_dLinks\0i_nLinkArraySize\0Doc_set_obj_name\0i_bsName\0"
    "Doc_set_obj_posture\0i_nPostureArraySize\0Doc_set_obj_velocity\0i_dVelocity\0"
    "Doc_set_obj_visibility\0i_bShow\0Math_trans_posture_to_rotationmatrix\0i_nType\0"
    "o_dTranslation\0PQAPIAddAbsJointPath\0i_dRobotJoints\0i_usRCount\0i_dGuideJoints\0"
    "i_usGCount\0i_dPositionerJoints\0i_usPCount\0i_dSpeedPercent\0i_nApproach\0"
    "i_nPointCount\0i_uPathID\0PQAPIAddCustomEvent\0i_uPointsID\0i_uExecuteObjID\0"
    "i_nEventPosition\0i_bsEventName\0i_bsContent\0PQAPIAddTransitPath\0i_uPathAID\0"
    "i_uPathBID\0o_PathID\0PQAPICalibratePart\0i_ulPartID\0i_dSrcPosition\0i_dDesPosition\0"
    "i_uCoordinateID\0PQAPICreateBoxPart\0i_dLength\0i_dWidth\0i_dHeight\0i_PartName\0"
    "o_PartID\0PQAPICreateCatchEvent\0i_uPartID\0i_uPointID\0i_bPrePoint\0i_bCatch\0"
    "i_EventName\0PQAPICreateExternalLink\0i_ulEngineID\0i_ulGuideID\0i_nAngle\0"
    "i_bSyncPosition\0i_ulPositionerID\0PQAPICreatePathCoordinateRelation\0i_ulPathID\0"
    "i_ulCoordinateID\0PQAPIDeleteExternalLink\0i_ulExternalID\0i_bClearAll\0"
    "PQAPIDeletePathGroup\0bsName\0PQAPIDeletePathGroupAll\0PQAPIFree\0qlonglong*\0"
    "i_ptrData\0PQAPIFreeArray\0i_ptrDataArray\0PQAPIGetActiveEngine\0o_uEngineID\0"
    "PQAPIGetExternalJointsFromPoints\0i_ulPointID\0i_uExternalID\0o_varJointsArray\0"
    "PQAPIGetObjPositionAttitudeType\0o_nType\0PQAPIGetPathFromRobot\0PQAPIGetPathStatus\0"
    "o_nStatus\0PQAPIGetPointCustomEventInfo\0i_uID\0o_bHasCustomEvent\0o_sContent\0"
    "o_sPosition\0PQAPIGetPointInfo\0i_nPostureCount\0o_dPointPosture\0o_dSpeedPercent\0"
    "o_nInstruct\0o_nApproach\0i_nPosType\0PQAPIGetPointsID\0o_varIDArray\0"
    "PQAPIGetRobotJointsFromPoints\0PQAPIGetWorkPartVertex\0i_nCount\0"
    "PQAPIGetWorkPartVertexCount\0PQAPIImportPointsToPath\0i_dPosition\0i_nInstruct\0"
    "i_PathName\0i_GroupName\0i_bToolEndPosture\0PQAPIInverseKinematics\0i_EndPosture\0"
    "i_nEndPostureCount\0io_pJointValues\0i_nJointValuesCount\0i_nAxisCfg\0i_nAxisCfgCount\0"
    "o_pPtStatus\0PQAPIInverseKinematicsFanuc\0PQAPIModifyExternalAxleBatch\0i_ulPathIDs\0"
    "i_nPathCount\0i_dExternalJoints\0PQAPIModifyPathGroupIndex\0bsSrcName\0bsTarName\0"
    "i_bBefore\0PQAPIModifyPointPosture\0PQAPIPutViewBGC\0i_dFromR\0i_dFromG\0i_dFromB\0"
    "i_dToR\0i_dToG\0i_dToB\0PQAPISetActiveEngine\0i_uEngineID\0PQAPISetAxisConfig6R\0"
    "PQAPISetOption\0struct_PQKitOption*\0i_stuOption\0PQAPISetPathInverType\0"
    "PQAPITransPosition\0i_dInputPosition\0i_nTargetType\0i_usCount\0o_dTargetPosition\0"
    "PQIKCalInverseKinematics6R\0i_nAxis1Cfg\0i_nAxis2Cfg\0i_nAxis4Cfg\0i_nAxis6Cfg\0"
    "Path_Set_Post_Coordinate\0Path_add_entry_point\0i_dInOffset\0i_dOutOffset\0"
    "i_nInInstruction\0i_nOutInstruction\0Path_change_order\0i_ulSrcPathID\0i_ulTarPathID\0"
    "i_bAhead\0Path_feature_set_round\0i_nTime\0Path_get_generate_face\0o_nFaceCount\0"
    "qlonglong**\0o_lpFacePtr\0Path_get_generate_shape\0o_nShapeCount\0o_lpShapePtr\0"
    "Path_get_group_path\0Path_get_point_count\0Path_get_pointgroup_info\0o_nPtGroupCount\0"
    "o_arrGroupPtCount\0Path_get_post_coordinate\0o_ulCoorID\0Path_get_relation_coordinate\0"
    "Path_get_tcp\0i_ulID\0wint_t**\0o_chTcpName\0Path_insert_from_joint\0i_nRobotJointsSize\0"
    "i_nGuideJointsSize\0i_nPositionerJointsSize\0Path_insert_from_point\0i_nPtCount\0"
    "Path_modify_external_axis\0i_nGuideCount\0i_dGuideData\0i_nGuideDataCount\0"
    "Path_set_tcp\0i_chTcpName\0Point_get_posture_batch\0i_nStartIndex\0double**\0"
    "o_dPosture\0Point_modify_poture_batch\0i_nEndIndex\0Robot_get_base_coordinate\0"
    "o_uCoordinateID\0Robot_get_end_posture\0Robot_get_tool\0o_ulToolID\0Tool_get_tcp\0"
    "o_nTcpCount\0o_chTcpNames\0Tool_get_tcp_posture\0LPSTR\0o_nPostureCount\0"
    "Tool_set_tcp_posture\0i_dTcpPosture\0pq_CloseComponent\0pq_CloseDocument\0"
    "i_bsDocName\0pq_GetAllDataObjectsByType\0i_lObjType\0o_sObjNames\0o_sObjIDs\0"
    "pq_GetDebugTreeView\0pq_GetModelTreeView\0pq_GetOutPutView\0pq_GetPlatformView\0"
    "hView\0pq_GetRobotControlView\0pq_InitPlatformComponent\0IPQPlatformComponentCallBack*\0"
    "pCallBack\0hParentHwnd\0bsPWD\0pq_RunCommand\0bsCommandID\0wParam\0lParam\0bsParam\0"
    "varParam\0qlonglong&\0lResult\0RPCLib::IPQPlatformComponent\0control\0"
    "RPCLib::IPQPlatformComponentCallBack\0Fire_Element_Pickup\0i_lEntityID\0"
    "i_nEntityType\0Fire_GetData_Result\0Fire_Initialize_Result\0Fire_LButton_Up\0"
    "i_lPosX\0i_lPosY\0Fire_Login_Result\0i_nLoginType\0Fire_Menu_Pop\0o_nHandled\0"
    "Fire_Path_Generate_Result\0i_bSuccess\0i_nIndex\0Fire_RButton_Up\0Fire_RunCMD_Result\0"
    "Notify_Raise_Dockwindow\0RPCLib::PQPlatformComponentCallBack\0IPQPlatformComponentCallBack\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_RPCLib__PQPlatformComponent[] = {

 // content:
    7, // revision
    0,  // classname
    1, 14, // classinfo
    105, 16, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 

// signal: name, argc, parameters, tag, flags
    3, 4, 541, 4, 5,
    9, 1, 550, 4, 5,
    11, 3, 553, 4, 5,

// slot: name, argc, parameters, tag, flags
    14, 4, 560, 4, 9,
    20, 0, 569, 4, 9,
    21, 5, 570, 4, 9,
    28, 3, 581, 4, 9,
    33, 5, 588, 4, 9,
    41, 3, 599, 4, 9,
    43, 2, 606, 4, 9,
    47, 1, 611, 4, 9,
    50, 3, 614, 4, 9,
    54, 2, 621, 4, 9,
    57, 2, 626, 4, 9,
    59, 2, 631, 4, 9,
    61, 2, 636, 4, 9,
    63, 3, 641, 4, 9,
    65, 3, 648, 4, 9,
    68, 2, 655, 4, 9,
    71, 2, 660, 4, 9,
    73, 2, 665, 4, 9,
    74, 2, 670, 4, 9,
    75, 2, 675, 4, 9,
    78, 4, 680, 4, 9,
    82, 3, 689, 4, 9,
    85, 3, 696, 4, 9,
    88, 2, 703, 4, 9,
    90, 4, 708, 4, 9,
    92, 3, 717, 4, 9,
    94, 2, 724, 4, 9,
    96, 3, 729, 4, 9,
    99, 12, 736, 4, 9,
    110, 6, 761, 4, 9,
    116, 3, 774, 4, 9,
    120, 4, 781, 4, 9,
    125, 8, 790, 4, 9,
    131, 5, 807, 4, 9,
    137, 5, 818, 4, 9,
    143, 2, 829, 4, 9,
    146, 3, 834, 4, 9,
    149, 2, 841, 4, 9,
    151, 1, 846, 4, 9,
    152, 1, 849, 4, 9,
    155, 1, 852, 4, 9,
    157, 1, 855, 4, 9,
    159, 3, 858, 4, 9,
    163, 2, 865, 4, 9,
    165, 3, 870, 4, 9,
    166, 2, 877, 4, 9,
    168, 5, 882, 4, 9,
    173, 8, 893, 4, 9,
    180, 2, 910, 4, 9,
    182, 2, 915, 4, 9,
    183, 4, 920, 4, 9,
    185, 2, 929, 4, 9,
    186, 11, 934, 4, 11,
    186, 12, 957, 4, 9,
    192, 9, 982, 4, 11,
    192, 10, 1001, 4, 9,
    200, 8, 1022, 4, 9,
    201, 5, 1039, 4, 9,
    205, 4, 1050, 4, 9,
    209, 3, 1059, 4, 11,
    209, 4, 1066, 4, 9,
    210, 6, 1075, 4, 9,
    217, 1, 1088, 4, 9,
    219, 3, 1091, 4, 9,
    220, 1, 1098, 4, 9,
    223, 2, 1101, 4, 9,
    224, 4, 1106, 4, 9,
    229, 10, 1115, 4, 9,
    234, 2, 1136, 4, 9,
    235, 5, 1141, 4, 9,
    240, 3, 1152, 4, 9,
    244, 2, 1159, 4, 9,
    246, 3, 1164, 4, 9,
    250, 3, 1171, 4, 9,
    253, 4, 1178, 4, 9,
    254, 2, 1187, 4, 9,
    255, 3, 1192, 4, 9,
    258, 2, 1199, 4, 9,
    260, 2, 1204, 4, 9,
    261, 2, 1209, 4, 9,
    265, 16, 1214, 4, 9,
    269, 13, 1247, 4, 9,
    271, 5, 1274, 4, 9,
    275, 2, 1285, 4, 9,
    277, 7, 1290, 4, 9,
    281, 6, 1305, 4, 9,
    283, 2, 1318, 4, 9,
    285, 3, 1323, 4, 9,
    286, 2, 1330, 4, 9,
    288, 3, 1335, 4, 9,
    291, 4, 1342, 4, 9,
    294, 5, 1351, 4, 9,
    296, 0, 1362, 4, 9,
    297, 1, 1363, 4, 9,
    299, 3, 1366, 4, 9,
    303, 0, 1373, 4, 9,
    304, 0, 1374, 4, 9,
    305, 0, 1375, 4, 9,
    306, 1, 1376, 4, 9,
    308, 0, 1379, 4, 9,
    309, 4, 1380, 4, 9,
    314, 6, 1389, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, 0x80000000 | 15, QMetaType::Int, 0x80000000 | 15, QMetaType::Int, 16, 17, 18, 19,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 15, QMetaType::Int, 0x80000000 | 15, QMetaType::Int, 0x80000000 | 26, 22, 23, 24, 25, 27,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 0x80000000 | 31, 29, 30, 32,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 39, 34, 35, 37, 38, 40,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, 42, 35, 37,
    QMetaType::Void, 0x80000000 | 31, 0x80000000 | 45, 44, 46,
    QMetaType::Void, 0x80000000 | 48, 49,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 26, 0x80000000 | 26, 51, 52, 53,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 55, 56,
    0x80000000 | 36, QMetaType::UInt, 0x80000000 | 31, 55, 58,
    0x80000000 | 36, QMetaType::UInt, 0x80000000 | 31, 55, 60,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 48, 55, 62,
    0x80000000 | 36, QMetaType::UInt, QMetaType::Int, 0x80000000 | 31, 55, 35, 64,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 36, 55, 66, 67,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 26, 69, 70,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, 55, 72,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, 55, 72,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, 55, 72,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 76, 77,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, QMetaType::Double, QMetaType::Double, 55, 79, 80, 81,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 55, 83, 84,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 55, 86, 87,
    QMetaType::Void, QMetaType::UInt, QMetaType::QString, 55, 89,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 55, 37, 91, 35,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, QMetaType::Double, 55, 93, 72,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 55, 95,
    QMetaType::Void, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, 37, 97, 98,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::UInt, 0x80000000 | 36, QMetaType::UInt, 0x80000000 | 36, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::Int, QMetaType::UInt, 69, 100, 101, 102, 103, 104, 105, 93, 106, 107, 108, 109,
    QMetaType::Void, 0x80000000 | 15, QMetaType::Int, QMetaType::UInt, QMetaType::Int, QMetaType::QString, QMetaType::QString, 111, 108, 112, 113, 114, 115,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 0x80000000 | 15, 117, 118, 119,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 36, QMetaType::UInt, 121, 122, 123, 124,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::QString, 0x80000000 | 15, 126, 127, 128, 79, 80, 81, 129, 130,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, QMetaType::Int, QMetaType::QString, 132, 133, 134, 135, 136,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, QMetaType::Int, QMetaType::UInt, 138, 139, 140, 141, 142,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 144, 145,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, 138, 147, 148,
    QMetaType::Void, QMetaType::UInt, QMetaType::QString, 69, 150,
    QMetaType::Void, QMetaType::UInt, 69,
    QMetaType::Void, 0x80000000 | 153, 154,
    QMetaType::Void, 0x80000000 | 153, 156,
    QMetaType::Void, 0x80000000 | 15, 158,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 0x80000000 | 26, 160, 161, 162,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 55, 164,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 48, 0x80000000 | 48, 69, 52, 53,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 144, 167,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 48, 0x80000000 | 48, 0x80000000 | 48, 169, 170, 49, 171, 172,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, 0x80000000 | 31, QMetaType::Int, 133, 174, 175, 66, 176, 177, 178, 179,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 26, 109, 181,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 26, 160, 162,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, 121, 124, 184, 122,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 121, 56,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 31, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::UInt, 0x80000000 | 15, 69, 187, 188, 93, 106, 107, 108, 189, 190, 124, 119,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 31, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::UInt, 0x80000000 | 15, QMetaType::Int, 69, 187, 188, 93, 106, 107, 108, 189, 190, 124, 119, 191,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 31, QMetaType::Int, 0x80000000 | 31, 69, 193, 194, 35, 195, 196, 197, 198, 199,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 31, QMetaType::Int, 0x80000000 | 31, QMetaType::Int, 69, 193, 194, 35, 195, 196, 197, 198, 199, 191,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 31, QMetaType::Int, 0x80000000 | 31, 69, 193, 194, 195, 196, 197, 198, 199,
    QMetaType::Void, 0x80000000 | 15, QMetaType::Int, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 202, 203, 147, 204, 58,
    QMetaType::Void, QMetaType::UInt, QMetaType::QString, QMetaType::QString, QMetaType::Int, 69, 206, 207, 208,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 160, 37, 91,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 160, 37, 91, 35,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 211, 212, 213, 214, 215, 216,
    QMetaType::Void, QMetaType::UInt, 218,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, QMetaType::Int, 109, 197, 198,
    QMetaType::Void, 0x80000000 | 221, 222,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 109, 97,
    QMetaType::Void, 0x80000000 | 36, QMetaType::Int, QMetaType::UInt, 0x80000000 | 36, 225, 226, 227, 228,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 31, 69, 193, 194, 195, 196, 230, 231, 232, 233, 199,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 144, 42,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, QMetaType::Double, QMetaType::Int, QMetaType::Int, 144, 236, 237, 238, 239,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, 241, 242, 243,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 144, 245,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 248, 144, 247, 249,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 248, 144, 251, 252,
    QMetaType::Void, QMetaType::UInt, QMetaType::QString, 0x80000000 | 26, 0x80000000 | 26, 69, 190, 52, 53,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 144, 56,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 26, 144, 256, 257,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, 144, 259,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, 144, 259,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 263, 262, 264,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 0x80000000 | 31, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::QString, QMetaType::QString, QMetaType::UInt, 0x80000000 | 15, 69, 100, 266, 102, 267, 104, 268, 108, 188, 93, 106, 107, 189, 190, 124, 119,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 31, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::QString, QMetaType::QString, QMetaType::UInt, QMetaType::Int, 0x80000000 | 15, 69, 270, 187, 179, 188, 93, 106, 107, 189, 190, 124, 191, 119,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 144, 139, 272, 273, 274,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 39, 262, 276,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 279, 144, 278, 184, 35, 124, 64, 280,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 144, 278, 282, 37, 91, 35,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, 69, 284,
    0x80000000 | 36, QMetaType::UInt, QMetaType::Int, 0x80000000 | 31, 55, 35, 64,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, 69, 287,
    0x80000000 | 31, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 263, 262, 289, 290,
    0x80000000 | 36, QMetaType::UInt, 0x80000000 | 292, QMetaType::Int, 0x80000000 | 31, 55, 276, 35, 293,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 292, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 55, 276, 295, 91, 35,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 298,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 48, 0x80000000 | 48, 300, 301, 302,
    QMetaType::ULongLong,
    QMetaType::ULongLong,
    QMetaType::ULongLong,
    QMetaType::Void, 0x80000000 | 31, 307,
    QMetaType::ULongLong,
    QMetaType::Void, 0x80000000 | 310, QMetaType::Int, QMetaType::QString, QMetaType::QString, 311, 312, 150, 313,
    QMetaType::Void, QMetaType::QString, QMetaType::ULongLong, QMetaType::LongLong, QMetaType::QString, QMetaType::QVariant, 0x80000000 | 320, 315, 316, 317, 318, 319, 321,

    0 // eod
};

const QMetaObject PQPlatformComponent::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_RPCLib__PQPlatformComponent, 0, 0, 0 }
};

void *PQPlatformComponent::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "RPCLib::PQPlatformComponent"))
        return static_cast<void*>(const_cast<PQPlatformComponent*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_RPCLib__IPQPlatformComponent[] = {

 // content:
    7, // revision
    322,  // classname
    0, 0, // classinfo
    105, 14, // methods
    1, 1400, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 539, 4, 5,
    9, 1, 548, 4, 5,
    11, 3, 551, 4, 5,

// slot: name, argc, parameters, tag, flags
    14, 4, 558, 4, 9,
    20, 0, 567, 4, 9,
    21, 5, 568, 4, 9,
    28, 3, 579, 4, 9,
    33, 5, 586, 4, 9,
    41, 3, 597, 4, 9,
    43, 2, 604, 4, 9,
    47, 1, 609, 4, 9,
    50, 3, 612, 4, 9,
    54, 2, 619, 4, 9,
    57, 2, 624, 4, 9,
    59, 2, 629, 4, 9,
    61, 2, 634, 4, 9,
    63, 3, 639, 4, 9,
    65, 3, 646, 4, 9,
    68, 2, 653, 4, 9,
    71, 2, 658, 4, 9,
    73, 2, 663, 4, 9,
    74, 2, 668, 4, 9,
    75, 2, 673, 4, 9,
    78, 4, 678, 4, 9,
    82, 3, 687, 4, 9,
    85, 3, 694, 4, 9,
    88, 2, 701, 4, 9,
    90, 4, 706, 4, 9,
    92, 3, 715, 4, 9,
    94, 2, 722, 4, 9,
    96, 3, 727, 4, 9,
    99, 12, 734, 4, 9,
    110, 6, 759, 4, 9,
    116, 3, 772, 4, 9,
    120, 4, 779, 4, 9,
    125, 8, 788, 4, 9,
    131, 5, 805, 4, 9,
    137, 5, 816, 4, 9,
    143, 2, 827, 4, 9,
    146, 3, 832, 4, 9,
    149, 2, 839, 4, 9,
    151, 1, 844, 4, 9,
    152, 1, 847, 4, 9,
    155, 1, 850, 4, 9,
    157, 1, 853, 4, 9,
    159, 3, 856, 4, 9,
    163, 2, 863, 4, 9,
    165, 3, 868, 4, 9,
    166, 2, 875, 4, 9,
    168, 5, 880, 4, 9,
    173, 8, 891, 4, 9,
    180, 2, 908, 4, 9,
    182, 2, 913, 4, 9,
    183, 4, 918, 4, 9,
    185, 2, 927, 4, 9,
    186, 11, 932, 4, 11,
    186, 12, 955, 4, 9,
    192, 9, 980, 4, 11,
    192, 10, 999, 4, 9,
    200, 8, 1020, 4, 9,
    201, 5, 1037, 4, 9,
    205, 4, 1048, 4, 9,
    209, 3, 1057, 4, 11,
    209, 4, 1064, 4, 9,
    210, 6, 1073, 4, 9,
    217, 1, 1086, 4, 9,
    219, 3, 1089, 4, 9,
    220, 1, 1096, 4, 9,
    223, 2, 1099, 4, 9,
    224, 4, 1104, 4, 9,
    229, 10, 1113, 4, 9,
    234, 2, 1134, 4, 9,
    235, 5, 1139, 4, 9,
    240, 3, 1150, 4, 9,
    244, 2, 1157, 4, 9,
    246, 3, 1162, 4, 9,
    250, 3, 1169, 4, 9,
    253, 4, 1176, 4, 9,
    254, 2, 1185, 4, 9,
    255, 3, 1190, 4, 9,
    258, 2, 1197, 4, 9,
    260, 2, 1202, 4, 9,
    261, 2, 1207, 4, 9,
    265, 16, 1212, 4, 9,
    269, 13, 1245, 4, 9,
    271, 5, 1272, 4, 9,
    275, 2, 1283, 4, 9,
    277, 7, 1288, 4, 9,
    281, 6, 1303, 4, 9,
    283, 2, 1316, 4, 9,
    285, 3, 1321, 4, 9,
    286, 2, 1328, 4, 9,
    288, 3, 1333, 4, 9,
    291, 4, 1340, 4, 9,
    294, 5, 1349, 4, 9,
    296, 0, 1360, 4, 9,
    297, 1, 1361, 4, 9,
    299, 3, 1364, 4, 9,
    303, 0, 1371, 4, 9,
    304, 0, 1372, 4, 9,
    305, 0, 1373, 4, 9,
    306, 1, 1374, 4, 9,
    308, 0, 1377, 4, 9,
    309, 4, 1378, 4, 9,
    314, 6, 1387, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, 0x80000000 | 15, QMetaType::Int, 0x80000000 | 15, QMetaType::Int, 16, 17, 18, 19,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 15, QMetaType::Int, 0x80000000 | 15, QMetaType::Int, 0x80000000 | 26, 22, 23, 24, 25, 27,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 0x80000000 | 31, 29, 30, 32,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 39, 34, 35, 37, 38, 40,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, 42, 35, 37,
    QMetaType::Void, 0x80000000 | 31, 0x80000000 | 45, 44, 46,
    QMetaType::Void, 0x80000000 | 48, 49,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 26, 0x80000000 | 26, 51, 52, 53,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 55, 56,
    0x80000000 | 36, QMetaType::UInt, 0x80000000 | 31, 55, 58,
    0x80000000 | 36, QMetaType::UInt, 0x80000000 | 31, 55, 60,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 48, 55, 62,
    0x80000000 | 36, QMetaType::UInt, QMetaType::Int, 0x80000000 | 31, 55, 35, 64,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 36, 55, 66, 67,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 26, 69, 70,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, 55, 72,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, 55, 72,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, 55, 72,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 76, 77,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, QMetaType::Double, QMetaType::Double, 55, 79, 80, 81,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 55, 83, 84,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 55, 86, 87,
    QMetaType::Void, QMetaType::UInt, QMetaType::QString, 55, 89,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 55, 37, 91, 35,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, QMetaType::Double, 55, 93, 72,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 55, 95,
    QMetaType::Void, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, 37, 97, 98,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::UInt, 0x80000000 | 36, QMetaType::UInt, 0x80000000 | 36, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::Int, QMetaType::UInt, 69, 100, 101, 102, 103, 104, 105, 93, 106, 107, 108, 109,
    QMetaType::Void, 0x80000000 | 15, QMetaType::Int, QMetaType::UInt, QMetaType::Int, QMetaType::QString, QMetaType::QString, 111, 108, 112, 113, 114, 115,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 0x80000000 | 15, 117, 118, 119,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 36, QMetaType::UInt, 121, 122, 123, 124,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::QString, 0x80000000 | 15, 126, 127, 128, 79, 80, 81, 129, 130,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, QMetaType::Int, QMetaType::QString, 132, 133, 134, 135, 136,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, QMetaType::Int, QMetaType::UInt, 138, 139, 140, 141, 142,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 144, 145,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, 138, 147, 148,
    QMetaType::Void, QMetaType::UInt, QMetaType::QString, 69, 150,
    QMetaType::Void, QMetaType::UInt, 69,
    QMetaType::Void, 0x80000000 | 153, 154,
    QMetaType::Void, 0x80000000 | 153, 156,
    QMetaType::Void, 0x80000000 | 15, 158,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 0x80000000 | 26, 160, 161, 162,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 55, 164,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 48, 0x80000000 | 48, 69, 52, 53,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 144, 167,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 48, 0x80000000 | 48, 0x80000000 | 48, 169, 170, 49, 171, 172,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, 0x80000000 | 31, QMetaType::Int, 133, 174, 175, 66, 176, 177, 178, 179,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 26, 109, 181,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 26, 160, 162,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, 121, 124, 184, 122,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 121, 56,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 31, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::UInt, 0x80000000 | 15, 69, 187, 188, 93, 106, 107, 108, 189, 190, 124, 119,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, 0x80000000 | 31, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::UInt, 0x80000000 | 15, QMetaType::Int, 69, 187, 188, 93, 106, 107, 108, 189, 190, 124, 119, 191,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 31, QMetaType::Int, 0x80000000 | 31, 69, 193, 194, 35, 195, 196, 197, 198, 199,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 31, QMetaType::Int, 0x80000000 | 31, QMetaType::Int, 69, 193, 194, 35, 195, 196, 197, 198, 199, 191,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 31, QMetaType::Int, 0x80000000 | 31, 69, 193, 194, 195, 196, 197, 198, 199,
    QMetaType::Void, 0x80000000 | 15, QMetaType::Int, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 202, 203, 147, 204, 58,
    QMetaType::Void, QMetaType::UInt, QMetaType::QString, QMetaType::QString, QMetaType::Int, 69, 206, 207, 208,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 160, 37, 91,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 160, 37, 91, 35,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 211, 212, 213, 214, 215, 216,
    QMetaType::Void, QMetaType::UInt, 218,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, QMetaType::Int, 109, 197, 198,
    QMetaType::Void, 0x80000000 | 221, 222,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 109, 97,
    QMetaType::Void, 0x80000000 | 36, QMetaType::Int, QMetaType::UInt, 0x80000000 | 36, 225, 226, 227, 228,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 31, 69, 193, 194, 195, 196, 230, 231, 232, 233, 199,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, 144, 42,
    QMetaType::Void, QMetaType::UInt, QMetaType::Double, QMetaType::Double, QMetaType::Int, QMetaType::Int, 144, 236, 237, 238, 239,
    QMetaType::Void, QMetaType::UInt, QMetaType::UInt, QMetaType::Int, 241, 242, 243,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 144, 245,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 248, 144, 247, 249,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 248, 144, 251, 252,
    QMetaType::Void, QMetaType::UInt, QMetaType::QString, 0x80000000 | 26, 0x80000000 | 26, 69, 190, 52, 53,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 144, 56,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 26, 144, 256, 257,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, 144, 259,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, 144, 259,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 263, 262, 264,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 0x80000000 | 31, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::QString, QMetaType::QString, QMetaType::UInt, 0x80000000 | 15, 69, 100, 266, 102, 267, 104, 268, 108, 188, 93, 106, 107, 189, 190, 124, 119,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 0x80000000 | 31, 0x80000000 | 36, 0x80000000 | 36, 0x80000000 | 31, QMetaType::QString, QMetaType::QString, QMetaType::UInt, QMetaType::Int, 0x80000000 | 15, 69, 270, 187, 179, 188, 93, 106, 107, 189, 190, 124, 191, 119,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, 144, 139, 272, 273, 274,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 39, 262, 276,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 279, 144, 278, 184, 35, 124, 64, 280,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, QMetaType::Int, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 144, 278, 282, 37, 91, 35,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, 69, 284,
    0x80000000 | 36, QMetaType::UInt, QMetaType::Int, 0x80000000 | 31, 55, 35, 64,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 15, 69, 287,
    0x80000000 | 31, QMetaType::UInt, 0x80000000 | 31, 0x80000000 | 263, 262, 289, 290,
    0x80000000 | 36, QMetaType::UInt, 0x80000000 | 292, QMetaType::Int, 0x80000000 | 31, 55, 276, 35, 293,
    QMetaType::Void, QMetaType::UInt, 0x80000000 | 292, 0x80000000 | 36, QMetaType::Int, QMetaType::Int, 55, 276, 295, 91, 35,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 298,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 48, 0x80000000 | 48, 300, 301, 302,
    QMetaType::ULongLong,
    QMetaType::ULongLong,
    QMetaType::ULongLong,
    QMetaType::Void, 0x80000000 | 31, 307,
    QMetaType::ULongLong,
    QMetaType::Void, 0x80000000 | 310, QMetaType::Int, QMetaType::QString, QMetaType::QString, 311, 312, 150, 313,
    QMetaType::Void, QMetaType::QString, QMetaType::ULongLong, QMetaType::LongLong, QMetaType::QString, QMetaType::QVariant, 0x80000000 | 320, 315, 316, 317, 318, 319, 321,

 // properties: name, type, flags
    323, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IPQPlatformComponent::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_RPCLib__IPQPlatformComponent, 0, 0, 0 }
};

void *IPQPlatformComponent::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "RPCLib::IPQPlatformComponent"))
        return static_cast<void*>(const_cast<IPQPlatformComponent*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_RPCLib__IPQPlatformComponentCallBack[] = {

 // content:
    7, // revision
    324,  // classname
    0, 0, // classinfo
    13, 14, // methods
    1, 148, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 79, 4, 5,
    9, 1, 88, 4, 5,
    11, 3, 91, 4, 5,

// slot: name, argc, parameters, tag, flags
    325, 3, 98, 4, 9,
    328, 1, 105, 4, 9,
    329, 1, 108, 4, 9,
    330, 2, 111, 4, 9,
    333, 1, 116, 4, 9,
    335, 4, 119, 4, 9,
    337, 4, 128, 4, 9,
    340, 2, 137, 4, 9,
    341, 1, 142, 4, 9,
    342, 1, 145, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, QMetaType::Int, 55, 326, 327,
    QMetaType::Void, QMetaType::Int, 321,
    QMetaType::Void, QMetaType::Int, 321,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 331, 332,
    QMetaType::Void, QMetaType::Int, 334,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, QMetaType::Int, 0x80000000 | 31, 55, 331, 332, 336,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::UInt, 338, 203, 339, 144,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 331, 332,
    QMetaType::Void, QMetaType::Int, 321,
    QMetaType::Void, QMetaType::Int, 97,

 // properties: name, type, flags
    323, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IPQPlatformComponentCallBack::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_RPCLib__IPQPlatformComponentCallBack, 0, 0, 0 }
};

void *IPQPlatformComponentCallBack::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "RPCLib::IPQPlatformComponentCallBack"))
        return static_cast<void*>(const_cast<IPQPlatformComponentCallBack*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_RPCLib__PQPlatformComponentCallBack[] = {

 // content:
    7, // revision
    343,  // classname
    1, 14, // classinfo
    13, 16, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 344, 

// signal: name, argc, parameters, tag, flags
    3, 4, 81, 4, 5,
    9, 1, 90, 4, 5,
    11, 3, 93, 4, 5,

// slot: name, argc, parameters, tag, flags
    325, 3, 100, 4, 9,
    328, 1, 107, 4, 9,
    329, 1, 110, 4, 9,
    330, 2, 113, 4, 9,
    333, 1, 118, 4, 9,
    335, 4, 121, 4, 9,
    337, 4, 130, 4, 9,
    340, 2, 139, 4, 9,
    341, 1, 144, 4, 9,
    342, 1, 147, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, QMetaType::Int, 55, 326, 327,
    QMetaType::Void, QMetaType::Int, 321,
    QMetaType::Void, QMetaType::Int, 321,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 331, 332,
    QMetaType::Void, QMetaType::Int, 334,
    QMetaType::Void, QMetaType::UInt, QMetaType::Int, QMetaType::Int, 0x80000000 | 31, 55, 331, 332, 336,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::UInt, 338, 203, 339, 144,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 331, 332,
    QMetaType::Void, QMetaType::Int, 321,
    QMetaType::Void, QMetaType::Int, 97,

    0 // eod
};

const QMetaObject PQPlatformComponentCallBack::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_RPCLib__PQPlatformComponentCallBack, 0, 0, 0 }
};

void *PQPlatformComponentCallBack::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "RPCLib::PQPlatformComponentCallBack"))
        return static_cast<void*>(const_cast<PQPlatformComponentCallBack*>(this));
    return QAxObject::qt_metacast(_clname);
}

