
CREATE TABLE `t_menu` (
  `id` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '菜单名称',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT = '菜单表';

CREATE TABLE `t_user` (
  `id` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `username` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户名',
  `passwd` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT = '用户表';

CREATE TABLE `t_user_menu` (
  `id` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `user_id` int NOT NULL   COMMENT '用户id',
  `memu_id` int NOT NULL  COMMENT '菜单id',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  FOREIGN KEY (user_id) REFERENCES t_user (id),
  FOREIGN KEY (memu_id) REFERENCES t_menu (id)
) COMMENT = '权限分配表';